version: '3'
services:
  mariadb:
     container_name: mariadb
     image: mariadb:mariadb
     networks:
       - inception
     build: 
       context: requirements/mariadb/
       dockerfile: Dockerfile
     env_file: .env
     volumes:
       - v_mariadb:/var/lib/mysql
     restart: on-failure
     healthcheck:
      test: "mysql -u${DB_USER} -p${DB_USER_PASSWORD} ${DB_NAME} -e 'SELECT 1'"
      interval : 1s
      retries: 10
  wordpress:
     container_name: wordpress
     image: wordpress:wordpress
     networks:
       - inception
     build: 
       context: requirements/wordpress/
       dockerfile: Dockerfile
     env_file: .env
     volumes:
       - v_wordpress:/var/www/html
     depends_on:
       mariadb:
         condition: service_healthy
     restart: on-failure
  nginx:
      container_name: nginx
      image: nginx:nginx
      networks:
       - inception
      build: 
        context: requirements/nginx/
        dockerfile: Dockerfile
      env_file: .env
      volumes: 
       - v_wordpress:/var/www/html
      depends_on:
       - wordpress
       - mariadb
      ports:
       - 443:443
      restart: on-failure 
networks:
  inception:
    driver: bridge
volumes:
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/masamoil/data/mariadb
  v_wordpress:
     driver: local
     driver_opts:
       type: none
       o: bind ## Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
       device: /home/masamoil/data/wordpress
